image: node:latest

stages:
  - test
  - e2e
  - deploy

# Cache modules in between jobs
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
  - node_modules/

before_script:
  - yarn install

run_tests:
  stage: test
  script:
    - yarn test

e2e_tests:
  stage: e2e
  image: circleci/node:latest-browsers
  script:
    - yarn build
    - yarn e2e
  artifacts:
    when: on_failure
    paths:
      - testcafe/screenshots/latest
      - testcafe/screenshots/diffs

pages:
  stage: deploy
  script:
    - yarn build-storybook
  artifacts:
    paths:
      - public