// flow-typed signature: 7ac4e4e030e5a408878992fed2c4b335
// flow-typed version: <<STUB>>/stylelint-selector-bem-pattern_v^2.0.0/flow_v0.89.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'stylelint-selector-bem-pattern'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'stylelint-selector-bem-pattern' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'stylelint-selector-bem-pattern/index' {
  declare module.exports: $Exports<'stylelint-selector-bem-pattern'>;
}
declare module 'stylelint-selector-bem-pattern/index.js' {
  declare module.exports: $Exports<'stylelint-selector-bem-pattern'>;
}
